### PR TITLE
New state machine implementation

### PR DESCRIPTION
**Pull request by mifrandir**
## Changes
1. Removed event-based model and implemented a simpler version.
2. Refactored to make transition behaviour understandable.
3. Renamed reset to shutdown.
4. Added braking buffer as a variable for Navigation.

Most of the changes were discussed and approved [here](https://github.com/Hyp-ed/hyped-2021/pull/16). This PR just applies them to the main branch.

## Aims
These changes are largely internal. They should not affect other projects in terms of functionality. They should, however, be of great help for members of the state machine team when it comes to adding features and changing the behaviour as well as other members of the software team when they need to understand or verify how state machine works.
Notably, we have not yet included anything related to LP/HP calibration as it is not ready and would break many interactions.

### CODE REVIEW

**Comment by MeinaLinWei** [comment]
Just finished reading it. Looks good to me.

**Comment by mifrandir** [comment]
> Just finished reading it. Looks good to me.

Could you please approve it then? (:

**Review by MeinaLinWei — APPROVED** [review]
Forgot to approve it last time ... (sorry!)

**Review by DonaldJennings — APPROVED** [review]
Look's all good to me 👍🏻

**Comment by mifrandir** [comment]
If no one points anything out until then, I will merge this before the meeting on Monday.

**Pull request merged**
