### PR TITLE
Implement full run tests

### PR DESCRIPTION
**Pull request by mifrandir**
We have now fully implemented tests that cover all possible scenarios from initialisation to shutdown.

To achieve this, we utilise two threads: for every test, we create a new state machine instance that runs in parallel to the testing thread. While the STM thread is untouched, the testing thread simulates the entirety of the pod (to the degree that is required to test state machine, i.e. we modify data in a way that enforces specific transitions) and also checks whether STM is doing what it's supposed to.

To achieve this we have implemented some helper methods that allow us to reuse checks that occur often, for example, to make sure the transition from Accelerating to NominalBraking works as intended:

```cpp
void testAcceleratingToNominalBraking()
{
  // Check initial state
  readData();
  enableOutput();
  ASSERT_EQ(stm_data.current_state, hyped::data::State::kAccelerating);
  disableOutput();

  // Randomise data
  randomiseInternally();

  // Prevent Accelerating -> FailureBraking
  embrakes_data.module_status           = ModuleStatus::kReady;
  nav_data.module_status                = ModuleStatus::kReady;
  telemetry_data.module_status          = ModuleStatus::kReady;
  motors_data.module_status             = ModuleStatus::kReady;
  sensors_data.module_status            = ModuleStatus::kReady;
  batteries_data.module_status          = ModuleStatus::kReady;
  telemetry_data.emergency_stop_command = false;

  // Enforce Accelerating -> NominalBraking
  nav_data.braking_distance = 1000;
  nav_data.displacement     = Navigation::kRunLength - nav_data.braking_distance;

  // Prevent NominalBraking -> Finished
  nav_data.velocity = 100;

  // Verify transition conditions are as intended
  bool has_emergency            = checkEmergency(log, embrakes_data, nav_data, batteries_data,
                                      telemetry_data, sensors_data, motors_data);
  bool has_entered_braking_zone = checkEnteredBrakingZone(log, nav_data);
  bool has_stopped              = checkPodStopped(log, nav_data);

  enableOutput();
  ASSERT_EQ(false, has_emergency);
  ASSERT_EQ(true, has_entered_braking_zone);
  ASSERT_EQ(false, has_stopped);
  disableOutput();

  // Let STM do its thing
  writeData();
  waitForUpdate();
  readData();

  // Check result
  enableOutput();
  ASSERT_EQ(stm_data.critical_failure, false) << accelerating_failure_error;
  ASSERT_EQ(stm_data.current_state, hyped::data::State::kNominalBraking)
    << accelerating_braking_transition_error;
  disableOutput();
}
```

Essentially all of these functions follow the same pattern:
1. Make sure the preconditions are met, e.g. we are in Accelerating.
2. Randomise the local copy of the central data structure. This is to make sure we don't miss something due to unwarranted assumptions.
3. Modify that local copy of the central data structure such that conditions for the desired transition are met. E.g. modify braking distance and displacement so that the pod is perceived to be in the braking zone.
4. Prevent any undesired transitions from the current state, e.g. set all the module statuses and the stop command to avoid detection of an emergency.
5. Prevent any undesired transitions from the target state. This would lead to more than one transition in a single step which would then not allow us to verify that all required states have been entered.
6. Use assertions to verify that 3-5 were successful by calling the checks from transition.cpp.
7. Write the local copy of the data to the global one, wait, read the global data into the local copy.
8. Make sure the transition happened as intended.

We then chain these helpers to create scenarios that can occur, i.e. paths through the state diagram. E.g. for a full run without emergencies:

```cpp
TEST_F(RunTest, nominalRun)
{
  for (int i = 0; i < TEST_SIZE; i++) {
    System &sys  = System::getSystem();
    sys.running_ = true;

    initialiseData();

    Thread *state_machine = new Main(0, stm_log);
    state_machine->start();

    waitForUpdate();

    testIdleToCalibrating();
    testCalibratingToReady();
    testReadyToAccelerating();
    testAcceleratingToNominalBraking();
    testNominalBrakingToFinished();
    testFinishedToOff();

    state_machine->join();
    delete state_machine;
  }
}
```

All of these scenarios look similar, too. In particular, we always get the system, set it to running, initialise the central data structure and create a new STM instance. We then have to wait for STM to run and set the initial state. After that, we can combine any sequence of helpers that lead from Idle to Off. When done, we wait for the thread to exit and delete it.

### CODE REVIEW

**Review by pmorande27 — COMMENTED** [review]
Overall it looks great, just need some comments to follow the style guide especially in run.test.cpp (Method comments)

**Review by robertasn — COMMENTED** [review]
Looks okay overall, but I'm not personally a fan of randomised tests, would like to see some edge cases being tested explicitly.

**Review by MeinaLinWei — APPROVED** [review]
Quite long to read through all the code but looks good to me.

**Comment by mifrandir** [comment]
> Looks okay overall, but I'm not personally a fan of randomised tests, would like to see some edge cases being tested explicitly.

That's a good point, though nothing here is *really* random, I'd say. Like, none of the randomised parts should affect the tests at all. E.g. what the central data structure says about some sensor readings should not be relevant so we're randomising it. This means there is no particular edge case that we need to test here. Is there something in particular you'd like to see?

**Comment by robertasn** [comment]
> > Looks okay overall, but I'm not personally a fan of randomised tests, would like to see some edge cases being tested explicitly.
> 
> That's a good point, though nothing here is _really_ random, I'd say. Like, none of the randomised parts should affect the tests at all. E.g. what the central data structure says about some sensor readings should not be relevant so we're randomising it. This means there is no particular edge case that we need to test here. Is there something in particular you'd like to see?

Don't know all the details to suggest a particular edge case. If there is nothing that's random, then why randomise the data and not use fixed values? Also, why it was chosen to run ten times each test?

**Comment by mifrandir** [comment]
> > > Looks okay overall, but I'm not personally a fan of randomised tests, would like to see some edge cases being tested explicitly.
> > 
> > 
> > That's a good point, though nothing here is _really_ random, I'd say. Like, none of the randomised parts should affect the tests at all. E.g. what the central data structure says about some sensor readings should not be relevant so we're randomising it. This means there is no particular edge case that we need to test here. Is there something, in particular, you'd like to see?
> 
> Don't know all the details to suggest a particular edge case. If there is nothing that's random, then why randomise the data and not use fixed values? Also, why it was chosen to run ten times each test?

The idea is that none of the randomise data is *supposed* to affect the outcome. We're randomising it to make sure we're not using any assumptions that might lead to undesired behaviour if they're not met. This is also to make this future-proof as I expect these tests to fail quite quickly if the state machine code is ever to be changed in a way that relies on certain conditions in `data`.

**Review by robertasn — APPROVED** [review]
> > > > Looks okay overall, but I'm not personally a fan of randomised tests, would like to see some edge cases being tested explicitly.
> > > 
> > > 
> > > That's a good point, though nothing here is _really_ random, I'd say. Like, none of the randomised parts should affect the tests at all. E.g. what the central data structure says about some sensor readings should not be relevant so we're randomising it. This means there is no particular edge case that we need to test here. Is there something, in particular, you'd like to see?
> > 
> > 
> > Don't know all the details to suggest a particular edge case. If there is nothing that's random, then why randomise the data and not use fixed values? Also, why it was chosen to run ten times each test?
> 
> The idea is that none of the randomise data is _supposed_ to affect the outcome. We're randomising it to make sure we're not using any assumptions that might lead to undesired behaviour if they're not met. This is also to make this future-proof as I expect these tests to fail quite quickly if the state machine code is ever to be changed in a way that relies on certain conditions in `data`.

I think this could also be achieved by having multiple unit tests that have min, max and somewhere in between (especially edge case) values. I believe that tests should be as deterministic as possible. In theory the randomisation won't influence the outcome of these tests, but you never know. In the end, I think your suggested use case and future-proofing is justified, so I'll approve it. It was just a thought for the future.

**Pull request merged**
